name: Bump version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        uses: rgryta/bump-my-version@action2
        with:
          args: "patch"
